"""
Interactive CLI chat client for the RAG Demo API.

Usage:
    python scripts/chat.py                        # connect to localhost:8000
    python scripts/chat.py --url http://HOST:8000  # connect to remote server

Commands during chat:
    /clear    — clear conversation history for this session
    /history  — show conversation history stored on the server
    /sources  — toggle display of retrieved source chunks
    /scores   — toggle display of RAGAS evaluation scores
    /quit     — exit

─────────────────────────────────────────────────────────────────────────────
HTTP API reference — you can call these endpoints directly with curl or any
HTTP client. Replace SESSION_ID with any unique string (e.g. "alice-session-1").
─────────────────────────────────────────────────────────────────────────────

# Check server health
#   curl http://localhost:8000/api/health

# Ask a question (POST /api/chat)
#   curl -s http://localhost:8000/api/chat \\
#        -H "Content-Type: application/json" \\
#        -d '{"session_id": "SESSION_ID", "question": "What is RAG?", "top_k": 5}' \\
#        | python -m json.tool

# View conversation history for a session
#   curl http://localhost:8000/api/sessions/SESSION_ID/history

# Clear history for a session
#   curl -X DELETE http://localhost:8000/api/sessions/SESSION_ID/clear

# Interactive API docs (auto-generated by FastAPI)
#   open http://localhost:8000/docs
─────────────────────────────────────────────────────────────────────────────
"""

import argparse
import json
import sys
import uuid

import requests


def print_scores(scores: dict) -> None:
    if not scores:
        return
    print("\n  RAGAS scores:")
    labels = {
        "faithfulness":      "Faithfulness      ",
        "answer_relevancy":  "Answer relevancy  ",
        "context_precision": "Context precision ",
    }
    for key, label in labels.items():
        val = scores.get(key)
        if val is not None:
            bar = "█" * int(val * 20)
            print(f"    {label} {val:.2f}  {bar}")


def print_sources(chunks: list[dict]) -> None:
    if not chunks:
        return
    print("\n  Retrieved chunks:")
    for i, c in enumerate(chunks, 1):
        source = c.get("source", "?")
        score = c.get("score", 0.0)
        preview = c.get("text", "")[:120].replace("\n", " ")
        print(f"    [{i}] {source}  (score {score:.3f})")
        print(f"        {preview}…")


def chat_loop(base_url: str, session_id: str, show_sources: bool, show_scores: bool) -> None:
    print(f"RAG Demo CLI  —  session {session_id}")
    print(f"Server: {base_url}")
    print("Commands: /clear  /history  /sources  /scores  /quit")
    print("─" * 60)

    while True:
        try:
            question = input("\nYou: ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\nBye.")
            break

        if not question:
            continue

        if question == "/quit":
            print("Bye.")
            break

        if question == "/clear":
            r = requests.delete(f"{base_url}/api/sessions/{session_id}/clear", timeout=10)
            r.raise_for_status()
            print("  History cleared.")
            continue

        if question == "/history":
            r = requests.get(f"{base_url}/api/sessions/{session_id}/history", timeout=10)
            r.raise_for_status()
            ctx = r.json().get("context", "(empty)")
            print(f"\n  History:\n{ctx}")
            continue

        if question == "/sources":
            show_sources = not show_sources
            print(f"  Sources display: {'on' if show_sources else 'off'}")
            continue

        if question == "/scores":
            show_scores = not show_scores
            print(f"  RAGAS scores display: {'on' if show_scores else 'off'}")
            continue

        payload = {"session_id": session_id, "question": question, "top_k": 5}
        try:
            r = requests.post(f"{base_url}/api/chat", json=payload, timeout=120)
            r.raise_for_status()
        except requests.exceptions.ConnectionError:
            print(f"  ERROR: cannot reach {base_url} — is the server running?")
            continue
        except requests.exceptions.HTTPError as e:
            print(f"  ERROR: {e}")
            continue

        data = r.json()
        print(f"\nAssistant: {data['answer']}")

        if show_scores:
            print_scores(data.get("ragas_scores", {}))

        if show_sources:
            print_sources(data.get("chunks", []))


def main() -> None:
    parser = argparse.ArgumentParser(description="RAG Demo CLI chat client")
    parser.add_argument("--url", default="http://localhost:8000", help="API base URL")
    parser.add_argument("--session", default=None, help="Session ID (auto-generated if omitted)")
    parser.add_argument("--no-scores", action="store_true", help="Hide RAGAS scores")
    parser.add_argument("--no-sources", action="store_true", help="Hide retrieved sources")
    args = parser.parse_args()

    session_id = args.session or str(uuid.uuid4())

    # Quick health check
    try:
        r = requests.get(f"{args.url}/api/health", timeout=5)
        r.raise_for_status()
        info = r.json()
        print(f"Connected  —  backend: {info.get('llm_backend', '?')}")
    except Exception as e:
        print(f"ERROR: could not connect to {args.url}/api/health — {e}")
        sys.exit(1)

    chat_loop(
        base_url=args.url,
        session_id=session_id,
        show_sources=not args.no_sources,
        show_scores=not args.no_scores,
    )


if __name__ == "__main__":
    main()
